dist: trusty
sudo: false
language: node_js
cache: yarn
node_js:
- '7'
- '6'
- '4'
notifications:
  email: false
  pushover:
    api_key:
      secure: snr/n8RmIC82OnN+7RXCvmEXmBEQjWb1vQqA5Wd9RZlIwJr9/QBuOaNpvk/d32jYyQf9/XM9Q5Teb1SqkrdRLab1CbM9rjC/rmCl49FvK6khWXihbasmkgg2LDpStBea9DZjjcaGfAsqnoybtfu/R4RSrIfxs/maI2apQK7jmNNuwrmUGfjWhi6hqQCFZe4Jbv4zGij+w3UzwCUlI/nerUVqv+peNB6PN8uJTDgG7TWmZQ+KwrqxVcyaMUjauC7I2splwq7mZFoLV1y3aaMR6WEjhw46MQEo/q8apJyaZsx0/XLyeME93w+okXcdEj+Mz13LOnTjjulhRpou6j15VqxHMakbcxJVjs1JsBXiGLq9CTdfbmCWUgYcAtHyzarwBG9mfx/H48GlXA89Qurqdl0szntsVHlldaYqCH1H24YiEl62xJHGs/xFqHRecjeYIrvaWey3mHZizaNVAYhHjfAaizRpykGFA2GOS7BD9AGT1DFD1qN1or4TOyGQB750/kgITrLRF+IIIl0wmLtEE2egVM9bddJ1uD6i4mksmBruOrtBcq/Tj6TutFlyAR7YyrntDl5Coo5Y6TRLsEvrX8n4sxhy+E8//xq2xgPvvtQPWlkCPe0aorS10GBrxrLyaUNdiMxRftA2tXLIu9ru34JJGFtdNuKu3YFcUmF8Cp4=
    users:
      secure: J7/ULOasce5yEjGQ4rwf7xHPCtzqJFoMr8w3p+JK+Ov8f4nQBOGD89fkz5qWTytwWlUfG130VVkv24Ldbq5yvVafRb43WiXsCvgt1GHR4biQZDVwe+XHkjL1KcPse+/khmSpF1/9rhFbFkCBWd9BUpYKr2YX+vz5N60jStYnyxSM9R1Vzn5ScE+EQrPhXrVPPsoF2LLN/4xrbFPuz+QNc+LEgR68tiax8EWnAh4XSk1z/s7VKM798UGpvF+XQJRc8/0vrjh9bTVJoCJ+5RNJz88JAkMjLdF4kU1GtS3QyT6nKxiSi4bF4JHy2ov5XDVFquxJtyrDYTEz7GmWTRYf4Tco6is/8qBZiTGBHq4MqPs+7VwIpO4ECoSkfSluxXiBsKAPhVOA/jZuRyN1oKWoJBTpz2rnBDQG/RE/4vzlKAZ2BJytjF38k59eyfHZPDw7m+Rx6ehWAk0fB08OEJP+8x1YlvJ2kcGSefEcwpEIuDhEXXpwlkcULtx0RWnqdSdn4Q6WAHzqckEyotyUPgnxLwlEVqSbiKr8FW9V5Bx0I/p/dWRtKhnxYBou2/Z88+uRET355niUQNW0etETfXYvKIrjesrPRGq95u+286fPZtx4aZobcWJ+/2u3CFiUr1ZrHpv7ZwjvXedS6C5XGEr/QQqA3DHN936zNAzwAAtH6UM=
